version: "3.7"

services:
  postgres:
    build: "./database"
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: cqrsproject10
      POSTGRES_DB: cqrsdb
    restart: always
  nats:
    image: "nats-streaming:0.9.2"
    restart: always
  elasticSearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:6.2.3"
    environment:
      - "discovery.type=single-node"
  feed:
    build: "."
    command: "feed-service"
    depends_on:
      - "postgres"
      - "nats"
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER: POSTGRES
      - POSTGRES_PASSWORD: cqrsproject10
      - POSTGRES_DB: cqrsdb
      - NATS_ADDRESS: "nats:4222"
  query:
    build: "."
    command: "query-service"
    depends_on:
      - "nats"
      - "postgres"
      - "elasticSearch"
    ports:
      - "8080"
    environment:
      - POSTGRES_USER: POSTGRES
      - POSTGRES_PASSWORD: cqrsproject10
      - POSTGRES_DB: cqrsdb
      - NATS_ADDRESS: "nats:4222"
      - ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  pusher:
    build: "."
    ports:
      - "8080"
    command: "pusher"
    depends_on:
      - "nats"
    environment:
      - "NATS_ADDRESS": "nats4222"
  nginx:
    build: "./nginx"
    ports:
      - "8080:80"
    depends_on:
      - feed
      - query
      - pusher
  
